In [24]:
#Examen
import numpy as np
from scipy import ndimage
from scipy import misc
import pandas as pd
import os

In [2]:
## 2) Crear un vector de ceros de tamaño 10

vector_de_ceros = np.zeros(10)
vector_de_ceros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
## 3) Crear un vector de ceros de tamaño 10 y el de la posicion 5 sea igual a 1
vector_de_ceros_dos = np.zeros(10)
vector_de_ceros_dos[4] = 1 
vector_de_ceros_dos

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [4]:
## 4) Cambiar el orden de un vector de 50 elementos, el de la posicion 1 es el de la 50 etc.
vector_50_elementos = np.arange(50)
print(vector_50_elementos[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [5]:
## 5) Crear una matriz de 3 x 3 con valores del cero al 8
matriz_3x3 = np.random.randint(0,9, size=(3,3))
matriz_3x3

array([[5, 4, 5],
       [6, 0, 3],
       [3, 8, 3]])

In [6]:
## 6) Encontrar los indices que no sean cero en un arreglo
arreglo = [1,2,0,0,4,0]
no_ceros = np.where(arreglo != 0)
no_ceros

(array([0], dtype=int64),)

In [7]:
## 7) Crear una matriz de identidad 3 x 3 
matriz_identidad_3x3 = np.eye(3)
matriz_identidad_3x3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
## 8) Crear una matriz 3 x 3 x 3 con valores randomicos
matriz3x3x3 = np.random.randint(0,9, size=(3,3,3))
matriz3x3x3

array([[[5, 3, 6],
        [3, 5, 2],
        [6, 0, 3]],

       [[8, 6, 8],
        [1, 4, 1],
        [5, 5, 8]],

       [[5, 3, 4],
        [7, 0, 2],
        [5, 0, 8]]])

In [9]:
## 9) Crear una matriz 10 x 10 y encontrar el mayor y el menor
matriz_10x10 = np.random.rand(10, 10)
num_mayor = matriz_10x10.max()
num_minimo = matriz_10x10.min()
matriz_10x10
print('mayor', num_mayor)
print('menor', num_minimo)

mayor 0.9964995275929506
menor 0.008161397809003046


In [10]:
## 10) Sacar los colores RGB unicos en una imagen (cuales rgb existen ej: 0, 0, 0 - 255,255,255 -> 2 colores)
mapache = misc.face()
color_1 = mapache.item(0,0,0)
color_2 = mapache.item(255,255,255)

IndexError: index 255 is out of bounds for axis 2 with size 3

In [11]:
## 11) ¿Como crear una serie de una lista, diccionario o arreglo?
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))

mylist_serie = pd.Series(mylist)
myarr_serie = pd.Series(myarr)
mydict = pd.Series(mydict)

mydict

a     0
b     1
c     2
e     3
d     4
f     5
g     6
h     7
i     8
j     9
k    10
l    11
m    12
n    13
o    14
p    15
q    16
r    17
s    18
t    19
u    20
v    21
w    22
x    23
y    24
z    25
dtype: int64

In [12]:
## 12) ¿Como convertir el indice de una serie en una columna de un DataFrame?

mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
ser = pd.Series(mydict)

In [13]:
## 13) ¿Como combinar varias series para hacer un DataFrame?
ser1 = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
ser2 = pd.Series(np.arange(26))

df_datos = {"letras": ser1, "numeros": ser2} 
df_combinacion = pd.DataFrame(df_datos)
print(df_combinacion)

   letras  numeros
0       a        0
1       b        1
2       c        2
3       e        3
4       d        4
5       f        5
6       g        6
7       h        7
8       i        8
9       j        9
10      k       10
11      l       11
12      m       12
13      n       13
14      o       14
15      p       15
16      q       16
17      r       17
18      s       18
19      t       19
20      u       20
21      v       21
22      w       22
23      x       23
24      y       24
25      z       25


In [14]:
## 14) ¿Como obtener los items que esten en una serie A y no en una serie B?
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

items_A = ser1[~ser1.isin(ser2)]

print(f"items\n{items_A}")

items
0    1
1    2
2    3
dtype: int64


In [15]:
## 15) ¿Como obtener los items que no son comunes en una serie A y serie B?
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

items_A = ser1[~ser1.isin(ser2)]
items_B = ser2[~ser2.isin(ser1)]
items_no_comunes = pd.concat([items_A, items_B])

print(f"no comunes\n{items_no_comunes}")

no comunes
0    1
1    2
2    3
2    6
3    7
4    8
dtype: int64


In [16]:
## 16) ¿Como obtener el numero de veces que se repite un valor en una serie?
ser = pd.Series(np.take(list('abcdefgh'), np.random.randint(8, size=30)))
print(ser)

0     d
1     c
2     e
3     h
4     b
5     d
6     a
7     d
8     f
9     e
10    d
11    c
12    g
13    a
14    f
15    a
16    g
17    a
18    b
19    a
20    a
21    c
22    a
23    d
24    g
25    f
26    g
27    b
28    d
29    f
dtype: object


In [17]:
## 17) ¿Como mantener los 2 valores mas repetidos de una serie, y a los demas valores cambiarles por 0 ?
np.random.RandomState(100)
ser = pd.Series(np.random.randint(1, 5, [12]))

valor_unicos = ser.unique()
valor_unicos

array([4, 3, 2, 1])

In [30]:
## 18) ¿Como transformar una serie de un arreglo de numpy a un DataFrame con un `shape` definido?

ser = pd.Series(np.random.randint(1, 10, 35))
#shape(7,5)
ser

0     6
1     8
2     4
3     5
4     3
5     8
6     6
7     5
8     6
9     7
10    2
11    1
12    2
13    5
14    2
15    1
16    3
17    6
18    2
19    3
20    4
21    6
22    4
23    1
24    7
25    7
26    1
27    6
28    1
29    3
30    1
31    5
32    3
33    1
34    8
dtype: int32

In [29]:
## 19) ¿Obtener los valores de una serie conociendo la posicion por indice?
ser = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))
pos = [0, 4, 8, 14, 20]
# a e i o u
ser2 =pd.Series(ser,index=[0,4,8,14,20]) 

In [22]:
## 20) ¿Como anadir series vertical u horizontalmente a un DataFrame?
ser1 = pd.Series(range(5))
ser2 = pd.Series(list('abcde'))
df_ser1 = pd.DataFrame(ser1)
df_ser2 = pd.DataFrame(ser2)

df_vertical = pd.concat([df_ser1, df_ser2], axis=0)
df_vertical

df_horizontal = pd.concat([df_ser1, df_ser2], axis=1)
df_horizontal

0  0
0  0  a
1  1  b
2  2  c
3  3  d
4  4  e

In [26]:
## 21)¿Obtener la media de una serie agrupada por otra serie?
frutas = pd.Series(np.random.choice(['manzana', 'banana', 'zanahoria'], 10))
pesos = pd.Series(np.linspace(1, 10, 10))
print(pesos.tolist())
print(frutas.tolist())

[1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0]
['manzana', 'zanahoria', 'zanahoria', 'manzana', 'manzana', 'banana', 'zanahoria', 'banana', 'banana', 'banana']


In [25]:
## 22)¿Como importar solo columnas especificas de un archivo csv?

path = "./Data/BostonHousing.csv"
df1 = pd.read_csv(path, nrows=10)
columnas = ['crim','zn', 'indus','chas']
df2 = pd.read_csv(path,nrows=10,usecols=columnas)